-- =========================================================
-- Créno : schéma initial
-- =========================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    phone         VARCHAR(30),
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('CLIENT', 'ADMIN'))
);

-- Prestations proposées par le commerce
CREATE TABLE services (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(120)  NOT NULL,
    description      VARCHAR(1000),
    duration_minutes INTEGER       NOT NULL,
    price_cents      INTEGER       NOT NULL,
    active           BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_services_duration CHECK (duration_minutes BETWEEN 5 AND 480),
    CONSTRAINT ck_services_price CHECK (price_cents >= 0)
);

-- Horaires d'ouverture hebdomadaires (plusieurs plages possibles par jour, ex. pause déjeuner)
CREATE TABLE opening_hours (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(10) NOT NULL,
    opens_at    TIME        NOT NULL,
    closes_at   TIME        NOT NULL,
    CONSTRAINT ck_opening_hours_day CHECK (day_of_week IN
        ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    CONSTRAINT ck_opening_hours_range CHECK (opens_at < closes_at)
);

-- Fermetures exceptionnelles (congés, jours fériés...), dates incluses
CREATE TABLE closures (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE         NOT NULL,
    end_date   DATE         NOT NULL,
    reason     VARCHAR(255),
    CONSTRAINT ck_closures_range CHECK (start_date <= end_date)
);

-- Rendez-vous
CREATE TABLE appointments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  BIGINT      NOT NULL REFERENCES users (id),
    service_id BIGINT      NOT NULL REFERENCES services (id),
    start_at   TIMESTAMPTZ NOT NULL,
    end_at     TIMESTAMPTZ NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'BOOKED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_appointments_range CHECK (start_at < end_at),
    CONSTRAINT ck_appointments_status CHECK (status IN ('BOOKED', 'COMPLETED', 'NO_SHOW', 'CANCELLED')),
    -- Garde-fou ultime contre la double réservation : deux RDV actifs
    -- ne peuvent jamais se chevaucher, même en cas de requêtes concurrentes.
    CONSTRAINT ex_appointments_no_overlap EXCLUDE USING gist (
        tstzrange(start_at, end_at, '[)') WITH &&
    ) WHERE (status = 'BOOKED')
);

CREATE INDEX idx_appointments_client ON appointments (client_id);
CREATE INDEX idx_appointments_start ON appointments (start_at);
CREATE INDEX idx_opening_hours_day ON opening_hours (day_of_week);
